# Site settings
title: Cassano Ristorante
email: apage516@gmail.com
description: Authentic Italian Dining in Happauge, NY
url: https://cassanoristorante.github.io
github_username: theanthonypage

# Build settings
markdown: kramdown
permalink: pretty
